### ISSUE TITLE
微信群？

### ISSUE THREAD

**Issue by brizer** [ykfe/imove#113]
不搞个微信群吗？走向国内开发者社区，微信也是很重要的吧？

**Comment by i5ting** [comment]
其实，不想扩张的太快，目前一些基础功能做的还不够。另外微信群，只有一周有效时间，超过200人就要手工加入。太麻烦了


![image](https://user-images.githubusercontent.com/3118295/123894488-d6f79580-d990-11eb-9697-87898f12175b.png)
