### ISSUE TITLE
增加新的通用元件

### ISSUE THREAD

**Issue by shenyinghe** [ykfe/imove#124]
问题①：内置的三种shape之外，可以自己增加新的shape吗？可能形状依旧是矩形但是带有自己的业务含义。

问题②：另外，通用元件的初始化能否从一个网络restful接口来获得，而不是打包固定的？

感谢！

**Comment by i5ting** [comment]
shape是按照x6的方式弄的，所以可以直接扩展的。

当下最麻烦的我问题是没有一个管理后台，管理节点，流程等做持久化

**Comment by shenyinghe** [comment]
“shape是按照x6的方式弄的，所以可以直接扩展的。”  --好的，我学习下先，问题先关闭了。

“管理后台”这是我现在准备做的，把imove看做一个lib的话只有前端好像并不是问题。

**Comment by i5ting** [comment]
你说的基本是对的，imove是一个创新尝试，已经达到预期效果了。能用，但不好用，主要是我们精力不足的原因


加油，可以开源出来一起玩

**Comment by jiyuyu** [comment]
> 

请问您是否实现了该功能？可以参考下吗
