### ISSUE TITLE
安装依赖失败

### ISSUE THREAD

**Issue by liswift** [ykfe/imove#83]
$ git clone https://github.com/imgcook/imove.git
Cloning into 'imove'...
remote: Enumerating objects: 97, done.
remote: Counting objects: 100% (97/97), done.
remote: Compressing objects: 100% (68/68), done.
remote: Total 2898 (delta 44), reused 61 (delta 29), pack-reused 2801
Receiving objects: 100% (2898/2898), 1.51 MiB | 941.00 KiB/s, done.
Resolving deltas: 100% (1583/1583), done.
node $ cd imove
imove (master) $ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: root@undefined
npm ERR! Found: rollup@2.38.5
npm ERR! node_modules/rollup
npm ERR!   dev rollup@"^2.6.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rollup@"^1.20.0" from rollup-plugin-size-snapshot@0.11.0
npm ERR! node_modules/rollup-plugin-size-snapshot
npm ERR!   dev rollup-plugin-size-snapshot@"^0.11.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See /Users/biquantan/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/biquantan/.npm/_logs/2021-02-08T10_26_56_003Z-debug.log

**Comment by liswift** [comment]
macOS 10.15.5
node v15.5.0
npm 7.5.2

**Comment by SmallStoneSK** [comment]
@liswift 

用 `npm install --legacy-peer-deps` 试试
