### ISSUE TITLE
fatal: 无法读取远程仓库。

### ISSUE THREAD

**Issue by heianxiyi** [ykfe/imove#92]
npm install

> postinstall
> lerna init && lerna bootstrap && npm link packages/cli

lerna notice cli v3.22.1
lerna info Updating package.json
lerna info Updating lerna.json
lerna info Creating packages directory
lerna success Initialized Lerna files
lerna notice cli v3.22.1
lerna info Bootstrapping 5 packages
lerna info Symlinking packages and binaries
lerna success Bootstrapped 5 packages
npm ERR! code 128
npm ERR! command failed
npm ERR! command git ls-remote ssh://git@github.com/packages/cli.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: 无法读取远程仓库。
npm ERR! 
npm ERR! 请确认您有正确的访问权限并且仓库存在。

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xiongxin/.npm/_logs/2021-03-08T06_58_30_024Z-debug.log
npm ERR! code 128
npm ERR! path /Users/xiongxin/code/imove
npm ERR! command failed
npm ERR! command sh -c lerna init && lerna bootstrap && npm link packages/cli

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xiongxin/.npm/_logs/2021-03-08T06_58_30_052Z-debug.log

**Comment by SmallStoneSK** [comment]
@heianxiyi 

是不是 github 的 ssh 配置有问题？可以参考这个看一下：https://gist.github.com/adamjohnson/5682757

**Comment by heianxiyi** [comment]
![image](https://user-images.githubusercontent.com/22736955/110722378-17e66580-824d-11eb-9ae5-d65e2b06df3b.png)
ssh没有问题，项目能运行起来，但我无法使用imove命令，只能通过手动指定到node_modules下的bin目录来执行imove命令

**Comment by SmallStoneSK** [comment]
@heianxiyi 

那你也可以用下面的命令全局安装

```bash
$ npm i @imove/cli -g
```
